services:
  avito-shop-service:
    build: ./deploy/develop
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
      - ${HOST_GOPATH}:/usr/go
    environment:
        # енвы подключения к БД
        - DATABASE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=password
        - DATABASE_NAME=shop
        - DATABASE_HOST=db
        # порт сервиса
        - SERVER_PORT=8080
    container_name: avito-shop-service
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://avito-shop-service:8080/health"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy
  

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      # "./migrations/init.sql" - путь к миграциям БД
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
    networks:
      - internal


  wait:
    image: hello-world:latest
    depends_on:
      avito-shop-service:
        condition: service_healthy

networks:
  internal:
    name: internal